name: Fork Message
on:
  fork:
    types: [created]

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment in discussions
        uses: peter-evans/create-discussion@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: inai-sandy/inAI-wiki
          category: General
          title: "Thanks for forking INAI!"
          body: |
            ğŸ‘‹ Thanks for forking **INAI**!  

            â­ Consider [starring the repo](https://github.com/inai-sandy/inAI-wiki/stargazers) to support the mission.  

            ğŸ’¡ You can also contribute by opening a PR:  
            ğŸ‘‰ [How to contribute](https://github.com/inai-sandy/inAI-wiki/blob/main/CONTRIBUTING.md)
