name: Fork Message
on:
  fork:
    types: [created]

permissions:                # ğŸ‘ˆ must be here, under "on:"
  discussions: write

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - name: Post thanks in Discussions
        uses: peter-evans/create-discussion@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: inai-sandy/inAI-wiki
          category: General
          title: "ğŸ‰ Thanks for forking INAI!"
          body: |
            ğŸ‘‹ Thanks for forking **INAI**!
            â­ Please consider starring the repo ğŸ‘‰ https://github.com/inai-sandy/inAI-wiki/stargazers
