name: Fork Message
on:
  fork:
    types: [created]

permissions:               # âœ… required to create Discussions
  discussions: write

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - name: Post thanks in Discussions
        uses: peter-evans/create-discussion@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: inai-sandy/inAI-wiki
          category: General      # ğŸ‘ˆ make sure you created a "General" category in Discussions
          title: "ğŸ‰ Thanks for forking INAI!"
          body: |
            ğŸ‘‹ Thanks for forking **INAI**!  

            â­ Please consider [starring the repo](https://github.com/inai-sandy/inAI-wiki/stargazers).  

            ğŸ’¡ You can also contribute:
            ğŸ‘‰ [How to contribute](https://github.com/inai-sandy/inAI-wiki/blob/main/CONTRIBUTING.md)
